apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl: {}
manifests: 
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: mortezadanaei/gams-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .