apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl: {}
manifests: 
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mortezadanaei/gams-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
            NODE_IMAGE: node:alpine
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mortezadanaei/gams-personnel
      context: personnel
      docker:
        dockerfile: Dockerfile
        buildArgs:
            NODE_IMAGE: node:alpine
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .