apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mortezadanaei/gams-auth:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: COOKIE_KEY1
              valueFrom:
                secretKeyRef:
                  name: cookie-secret1
                  key: COOKIE_KEY1
            - name: COOKIE_KEY2
              valueFrom:
                secretKeyRef:
                  name: cookie-secret2
                  key: COOKIE_KEY2
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
