name: GASM Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env: 
       CI: false       
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: auth
          push: true
          tags: mortezadanaei/gams-auth:latest

      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set MONGO_URI and JWT_KEY environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> $GITHUB_ENV

      - name: Deploy auth microservice to Kubernetes
        uses: kubernetes-actions/deploy@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          kubectl_version: v1.21.5
          helm_version: v3.7.0
          manifests: |
            auth-depl.yaml
            auth-srv.yaml
          manifests_path: infra/k8s
      - run: npm install
      - run: npm run start --prefix auth     